=== OpenBazaar/validation-obgo-tests/profileSchema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "peerID",
    "name",
    "nsfw",
    "vendor",
    "moderator",
    "stats",
    "bitcoinPubkey",
    "lastModified",
    "currencies"
  ],
  "properties": {
    "peerID": {
      "$id": "#/properties/peerID",
      "type": "string",
      "title": "The Peerid Schema",
      "default": "",
      "examples": [
        "QmVCJiuBY5RPw8wWU85AxzJRkpYZsvDpnYRyGe8opLRJX6"
      ],
      "pattern": "^(.*)$"
    },
    "handle": {
      "$id": "#/properties/handle",
      "type": "string",
      "title": "The Handle Schema",
      "default": "",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "The Name Schema",
      "default": "",
      "examples": [
        "v5 Seller"
      ],
      "pattern": "^(.*)$"
    },
    "location": {
      "$id": "#/properties/location",
      "type": "string",
      "title": "The Location Schema",
      "default": "",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "about": {
      "$id": "#/properties/about",
      "type": "string",
      "title": "The About Schema",
      "default": "",
      "examples": [
        "The Dude"
      ],
      "pattern": "^(.*)$"
    },
    "shortDescription": {
      "$id": "#/properties/shortDescription",
      "type": "string",
      "title": "The Shortdescription Schema",
      "default": "",
      "examples": [
        "Yo"
      ],
      "pattern": "^(.*)$"
    },
    "nsfw": {
      "$id": "#/properties/nsfw",
      "type": "boolean",
      "title": "The Nsfw Schema",
      "default": false,
      "examples": [
        false
      ]
    },
    "vendor": {
      "$id": "#/properties/vendor",
      "type": "boolean",
      "title": "The Vendor Schema",
      "default": false,
      "examples": [
        true
      ]
    },
    "moderator": {
      "$id": "#/properties/moderator",
      "type": "boolean",
      "title": "The Moderator Schema",
      "default": false,
      "examples": [
        false
      ]
    },
    "stats": {
      "$id": "#/properties/stats",
      "type": "object",
      "title": "The Stats Schema",
      "required": [
        "followerCount",
        "followingCount",
        "listingCount",
        "ratingCount",
        "postCount",
        "averageRating"
      ],
      "properties": {
        "followerCount": {
          "$id": "#/properties/stats/properties/followerCount",
          "type": "integer",
          "title": "The Followercount Schema",
          "default": 0,
          "examples": [
            7
          ]
        },
        "followingCount": {
          "$id": "#/properties/stats/properties/followingCount",
          "type": "integer",
          "title": "The Followingcount Schema",
          "default": 0,
          "examples": [
            0
          ]
        },
        "listingCount": {
          "$id": "#/properties/stats/properties/listingCount",
          "type": "integer",
          "title": "The Listingcount Schema",
          "default": 0,
          "examples": [
            2
          ]
        },
        "ratingCount": {
          "$id": "#/properties/stats/properties/ratingCount",
          "type": "integer",
          "title": "The Ratingcount Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "postCount": {
          "$id": "#/properties/stats/properties/postCount",
          "type": "integer",
          "title": "The Postcount Schema",
          "default": 0,
          "examples": [
            0
          ]
        },
        "averageRating": {
          "$id": "#/properties/stats/properties/averageRating",
          "type": "integer",
          "title": "The Averagerating Schema",
          "default": 0,
          "examples": [
            5
          ]
        }
      }
    },
    "bitcoinPubkey": {
      "$id": "#/properties/bitcoinPubkey",
      "type": "string",
      "title": "The Bitcoinpubkey Schema",
      "default": "",
      "examples": [
        "02657f97b89f6de761fc93c9e61c69d92d2db5fa565bc087476932549d2b103add"
      ],
      "pattern": "^(.*)$"
    },
    "lastModified": {
      "$id": "#/properties/lastModified",
      "type": "string",
      "title": "The Lastmodified Schema",
      "default": "",
      "examples": [
        "2019-10-22T00:56:15.841731088Z"
      ],
      "pattern": "^(.*)$"
    },
    "currencies": {
      "$id": "#/properties/currencies",
      "type": "array",
      "title": "The Currencies Schema",
      "items": {
        "$id": "#/properties/currencies/items",
        "type": "string",
        "title": "The Items Schema",
        "default": "",
        "examples": [
          "BCH",
          "ZEC",
          "LTC",
          "ETH",
          "BTC"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== OpenBazaar/validation-obgo-tests/responses/profile.json
{
    "peerID": "QmVCJiuBY5RPw8wWU85AxzJRkpYZsvDpnYRyGe8opLRJX6",
    "handle": "",
    "name": "v5 Seller",
    "location": "",
    "about": "The Dude",
    "shortDescription": "Yo",
    "nsfw": false,
    "vendor": true,
    "moderator": false,
    "stats": {
        "followerCount": 7,
        "followingCount": 0,
        "listingCount": 2,
        "ratingCount": 1,
        "postCount": 0,
        "averageRating": 5
    },
    "bitcoinPubkey": "02657f97b89f6de761fc93c9e61c69d92d2db5fa565bc087476932549d2b103add",
    "lastModified": "2019-10-22T00:56:15.841731088Z",
    "currencies": [
        "BCH",
        "ZEC",
        "LTC",
        "ETH",
        "BTC"
    ]
}
