=== OpenBazaar/validation-obgo-tests/schema/listingsSchema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "acceptedCurrencies",
      "averageRating",
      "categories",
      "coinType",
      "contractType",
      "description",
      "freeShipping",
      "hash",
      "language",
      "moderators",
      "nsfw",
      "price",
      "ratingCount",
      "shipsTo",
      "slug",
      "thumbnail",
      "title"
    ],
    "properties": {
      "acceptedCurrencies": {
        "$id": "#/items/properties/acceptedCurrencies",
        "type": "array",
        "title": "The Acceptedcurrencies Schema",
        "items": {
          "$id": "#/items/properties/acceptedCurrencies/items",
          "type": "string",
          "title": "The Items Schema",
          "default": "",
          "examples": [
            "BTC",
            "BCH",
            "LTC",
            "ZEC",
            "ETH"
          ],
          "pattern": "^(.*)$"
        }
      },
      "averageRating": {
        "$id": "#/items/properties/averageRating",
        "type": "integer",
        "title": "The Averagerating Schema",
        "default": 0,
        "examples": [
          0
        ]
      },
      "categories": {
        "$id": "#/items/properties/categories",
        "type": "array",
        "title": "The Categories Schema",
        "items": {
          "$id": "#/items/properties/categories/items",
          "type": "string",
          "title": "The Items Schema",
          "default": "",
          "examples": [
            "ðŸ‘š Apparel &amp; Accessories"
          ],
          "pattern": "^(.*)$"
        }
      },
      "coinType": {
        "$id": "#/items/properties/coinType",
        "type": "string",
        "title": "The Cointype Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "contractType": {
        "$id": "#/items/properties/contractType",
        "type": "string",
        "title": "The Contracttype Schema",
        "default": "",
        "examples": [
          "PHYSICAL_GOOD"
        ],
        "pattern": "^(.*)$"
      },
      "description": {
        "$id": "#/items/properties/description",
        "type": "string",
        "title": "The Description Schema",
        "default": "",
        "examples": [
          "This is a listing example for testing orders."
        ],
        "pattern": "^(.*)$"
      },
      "freeShipping": {
        "$id": "#/items/properties/freeShipping",
        "type": "array",
        "title": "The Freeshipping Schema",
        "items": {
          "$id": "#/items/properties/freeShipping/items",
          "type": "string",
          "title": "The Items Schema",
          "default": "",
          "examples": [
            "ALL"
          ],
          "pattern": "^(.*)$"
        }
      },
      "hash": {
        "$id": "#/items/properties/hash",
        "type": "string",
        "title": "The Hash Schema",
        "default": "",
        "examples": [
          "QmePjhYGVWf6Gqqz1NeLTfi8MooHPixWpsSQMyv73imHom"
        ],
        "pattern": "^(.*)$"
      },
      "language": {
        "$id": "#/items/properties/language",
        "type": "string",
        "title": "The Language Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "moderators": {
        "$id": "#/items/properties/moderators",
        "type": "array",
        "title": "The Moderators Schema",
        "items": {
          "$id": "#/items/properties/moderators/items",
          "type": "string",
          "title": "The Items Schema",
          "default": "",
          "examples": [
            "QmcdkKM2fWCKzTZdpjEY6abzRbDhRRJvNmqwNKVyiDtGky"
          ],
          "pattern": "^(.*)$"
        }
      },
      "modifier": {
        "$id": "#/items/properties/modifier",
        "type": "integer",
        "title": "The Modifier Schema",
        "default": 0,
        "examples": [
          0
        ]
      },
      "nsfw": {
        "$id": "#/items/properties/nsfw",
        "type": "boolean",
        "title": "The Nsfw Schema",
        "default": false,
        "examples": [
          false
        ]
      },
      "price": {
        "$id": "#/items/properties/price",
        "type": "object",
        "title": "The Price Schema",
        "required": [
          "amount",
          "currency"
        ],
        "properties": {
          "amount": {
            "$id": "#/items/properties/price/properties/amount",
            "type": "string",
            "title": "The Amount Schema",
            "default": "",
            "examples": [
              "100"
            ],
            "pattern": "^(.*)$"
          },
          "currency": {
            "$id": "#/items/properties/price/properties/currency",
            "type": "object",
            "title": "The Currency Schema",
            "required": [
              "code",
              "divisibility"
            ],
            "properties": {
              "code": {
                "$id": "#/items/properties/price/properties/currency/properties/code",
                "type": "string",
                "title": "The Code Schema",
                "default": "",
                "examples": [
                  "USD"
                ],
                "pattern": "^(.*)$"
              },
              "currencyType": {
                "$id": "#/items/properties/price/properties/currency/properties/currencyType",
                "type": "string",
                "title": "The Currencytype Schema",
                "default": "",
                "examples": [
                  "fiat"
                ],
                "pattern": "^(.*)$"
              },
              "divisibility": {
                "$id": "#/items/properties/price/properties/currency/properties/divisibility",
                "type": "integer",
                "title": "The Divisibility Schema",
                "default": 0,
                "examples": [
                  2
                ]
              },
              "name": {
                "$id": "#/items/properties/price/properties/currency/properties/name",
                "type": "string",
                "title": "The Name Schema",
                "default": "",
                "examples": [
                  "United States Dollar"
                ],
                "pattern": "^(.*)$"
              }
            }
          }
        }
      },
      "ratingCount": {
        "$id": "#/items/properties/ratingCount",
        "type": "integer",
        "title": "The Ratingcount Schema",
        "default": 0,
        "examples": [
          0
        ]
      },
      "shipsTo": {
        "$id": "#/items/properties/shipsTo",
        "type": "array",
        "title": "The Shipsto Schema",
        "items": {
          "$id": "#/items/properties/shipsTo/items",
          "type": "string",
          "title": "The Items Schema",
          "default": "",
          "examples": [
            "ALL"
          ],
          "pattern": "^(.*)$"
        }
      },
      "slug": {
        "$id": "#/items/properties/slug",
        "type": "string",
        "title": "The Slug Schema",
        "default": "",
        "examples": [
          "eth-physical-order-testing-w-options"
        ],
        "pattern": "^(.*)$"
      },
      "thumbnail": {
        "$id": "#/items/properties/thumbnail",
        "type": "object",
        "title": "The Thumbnail Schema",
        "required": [
          "medium",
          "small",
          "tiny"
        ],
        "properties": {
          "medium": {
            "$id": "#/items/properties/thumbnail/properties/medium",
            "type": "string",
            "title": "The Medium Schema",
            "default": "",
            "examples": [
              "QmTJfeeapZwFM8EoZAuf16JsSJyxZtKaAR6hmWiMf4CTcF"
            ],
            "pattern": "^(.*)$"
          },
          "small": {
            "$id": "#/items/properties/thumbnail/properties/small",
            "type": "string",
            "title": "The Small Schema",
            "default": "",
            "examples": [
              "QmVsoT9iabv6GZhxhvtjSpQMJA6QyMivGTs6MmHJr6TBm9"
            ],
            "pattern": "^(.*)$"
          },
          "tiny": {
            "$id": "#/items/properties/thumbnail/properties/tiny",
            "type": "string",
            "title": "The Tiny Schema",
            "default": "",
            "examples": [
              "QmbjyAxYee4y3443kAMLcmRVwggZsRDKiyXnXus1qdJJWz"
            ],
            "pattern": "^(.*)$"
          }
        }
      },
      "title": {
        "$id": "#/items/properties/title",
        "type": "string",
        "title": "The Title Schema",
        "default": "",
        "examples": [
          "ETH physical order testing w/ options"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== OpenBazaar/validation-obgo-tests/responses/listings.json
[
  {
    "acceptedCurrencies": [
      "BTC",
      "BCH",
      "LTC",
      "ZEC",
      "ETH"
    ],
    "averageRating": 0,
    "categories": [
      "ðŸ‘š Apparel &amp; Accessories"
    ],
    "coinType": "",
    "contractType": "PHYSICAL_GOOD",
    "description": "This is a listing example for testing orders.",
    "freeShipping": [
      "ALL"
    ],
    "hash": "QmePjhYGVWf6Gqqz1NeLTfi8MooHPixWpsSQMyv73imHom",
    "language": "",
    "moderators": [
      "QmcdkKM2fWCKzTZdpjEY6abzRbDhRRJvNmqwNKVyiDtGky"
    ],
    "modifier": 0,
    "nsfw": false,
    "price": {
      "amount": "100",
      "currency": {
        "code": "USD",
        "currencyType": "fiat",
        "divisibility": 2,
        "name": "United States Dollar"
      }
    },
    "ratingCount": 0,
    "shipsTo": [
      "ALL"
    ],
    "slug": "eth-physical-order-testing-w-options",
    "thumbnail": {
      "medium": "QmTJfeeapZwFM8EoZAuf16JsSJyxZtKaAR6hmWiMf4CTcF",
      "small": "QmVsoT9iabv6GZhxhvtjSpQMJA6QyMivGTs6MmHJr6TBm9",
      "tiny": "QmbjyAxYee4y3443kAMLcmRVwggZsRDKiyXnXus1qdJJWz"
    },
    "title": "ETH physical order testing w/ options"
  }
]
